version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: shopstr_web_1
      APP_PORT: 3000

  web:
    image: calvadev/shopstr:latest@sha256:46079165c7f1a868f5f6a950d1ffe5cf0f2eddeb1b19e53f8a39027ff3c9e565
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: 3000
