version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: shopstr_web_1
      APP_PORT: 3000

  web:
    image: calvadev/shopstr-eng:v0.1.0@sha256:776a9964ebabd94cbfa0d9763afa4f0a2>
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: 3000
